/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/kakao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 카카오 로그인/가입 (화이트리스트 검증) */
        post: operations["AuthController_kakao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 리프레시 토큰 회전 */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 (리프레시 토큰 무효화) */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보 + 온보딩 상태 */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 업로드용 presigned URL 발급 */
        post: operations["MediaController_createUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{mediaId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 업로드 완료 확정 (객체 존재 확인 + READY) */
        post: operations["MediaController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 미디어 메타데이터 + 다운로드 URL (권한 검증) */
        get: operations["MediaController_getMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 등록 사용자 검색 (닉네임) */
        get: operations["UsersController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자 프로필 조회 (같은 룸/연락처만) */
        get: operations["UsersController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 최초 온보딩 (닉네임/아바타/상태메시지) */
        post: operations["ProfileController_create"];
        delete?: never;
        options?: never;
        head?: never;
        /** 프로필 부분 수정 */
        patch: operations["ProfileController_update"];
        trace?: never;
    };
    "/api/v1/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 채팅방 목록 (최근 활동순, 미읽음 수 포함) */
        get: operations["RoomsController_list"];
        put?: never;
        /** 방 생성 (1:1 중복 시 기존 방 반환 / 그룹) */
        post: operations["RoomsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 방 상세 + 멤버 목록 */
        get: operations["RoomsController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 방 정보 수정 (그룹, OWNER/ADMIN) */
        patch: operations["RoomsController_update"];
        trace?: never;
    };
    "/api/v1/rooms/{roomId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 멤버 추가 (그룹, OWNER/ADMIN) */
        post: operations["RoomsController_addMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{roomId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 멤버 탈퇴(본인) 또는 추방(OWNER/ADMIN) */
        delete: operations["RoomsController_removeMember"];
        options?: never;
        head?: never;
        /** 멤버 역할 변경 (그룹, OWNER) */
        patch: operations["RoomsController_updateMemberRole"];
        trace?: never;
    };
    "/api/v1/rooms/{roomId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 메시지 이력 (커서 페이지네이션, seq < cursor 인 과거 메시지) */
        get: operations["MessagesController_list"];
        put?: never;
        /** 메시지 전송 (REST 폴백). 기본 전송은 WebSocket 사용 */
        post: operations["MessagesController_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{roomId}/messages/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 메시지 삭제(언센드) — 발신자 본인 */
        delete: operations["MessagesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{roomId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 읽음 위치 갱신 */
        post: operations["MessagesController_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/push/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** FCM 토큰 등록 */
        post: operations["PushController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/push/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** FCM 토큰 삭제 */
        delete: operations["PushController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/whitelist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 화이트리스트 목록 */
        get: operations["AdminController_list"];
        put?: never;
        /** 화이트리스트 등록/초대 */
        post: operations["AdminController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/whitelist/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 화이트리스트 삭제 */
        delete: operations["AdminController_remove"];
        options?: never;
        head?: never;
        /** 화이트리스트 상태 변경 (BLOCKED 시 세션 무효화) */
        patch: operations["AdminController_update"];
        trace?: never;
    };
    "/api/v1/admin/access-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 가입 대기 목록 (화이트리스트 미등록 로그인 시도) */
        get: operations["AccessRequestController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/access-requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 가입 승인 (화이트리스트 INVITED로 승격 + 대기열 제거) */
        post: operations["AccessRequestController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/access-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 가입 대기 항목 삭제 (거절/무시) */
        delete: operations["AccessRequestController_dismiss"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness (DB + Redis 연결 확인) */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DeviceDto: {
            /** @example iPhone 15 */
            name?: string;
            /** @enum {string} */
            platform?: "ios" | "android" | "web";
        };
        KakaoLoginDto: {
            /** @description 카카오 로그인 리다이렉트 콜백으로 받은 인가 코드(authorization code). 백엔드가 앱 시크릿과 함께 카카오 서버에 제출해 액세스 토큰으로 교환합니다. */
            code: string;
            /**
             * @description 인가 코드를 발급받을 때 사용한 redirect_uri. 카카오 토큰 교환 시 바이트 단위로 동일해야 합니다.
             * @example https://intaektalk.app/oauth/kakao/callback
             */
            redirectUri: string;
            device?: components["schemas"]["DeviceDto"];
        };
        LoginUserResponse: {
            id: string;
            /** @description 카카오 회원번호 */
            kakaoId: string;
        };
        LoginResponse: {
            /** @description 액세스 토큰(JWT) */
            accessToken: string;
            /** @description 리프레시 토큰(JWT, 회전 대상) */
            refreshToken: string;
            user: components["schemas"]["LoginUserResponse"];
            /** @description 온보딩(프로필 생성) 완료 여부 */
            isOnboarded: boolean;
        };
        RefreshDto: {
            refreshToken: string;
        };
        TokenPairResponse: {
            /** @description 액세스 토큰(JWT) */
            accessToken: string;
            /** @description 리프레시 토큰(JWT, 회전 대상) */
            refreshToken: string;
        };
        LogoutDto: {
            refreshToken: string;
        };
        MeProfileResponse: {
            nickname: string;
            statusMessage: string | null;
            avatarMediaId: string | null;
            /** @description 표시용 아바타 URL(없으면 null) */
            avatarUrl: string | null;
        };
        MeResponse: {
            id: string;
            /** @description 카카오 회원번호 */
            kakaoId: string;
            isOnboarded: boolean;
            /** @description 관리자 콘솔 접근 권한 여부(ADMIN_USER_IDS 기준) */
            isAdmin: boolean;
            /** @description 온보딩 전이면 null */
            profile: components["schemas"]["MeProfileResponse"] | null;
        };
        CreateUploadUrlDto: {
            /** @example image/gif */
            mimeType: string;
            /**
             * @description 바이트 크기
             * @example 1048576
             */
            byteSize: number;
            width?: number;
            height?: number;
            /** @description 동영상/애니메이션 길이(ms) */
            durationMs?: number;
        };
        UploadUrlResponse: {
            mediaId: string;
            /** @description 업로드용 presigned PUT URL */
            uploadUrl: string;
            /** @description 스토리지 객체 키 */
            storageKey: string;
        };
        MediaResponse: {
            mediaId: string;
            /** @description 다운로드(GET) URL */
            url: string;
            /** @description 썸네일 URL(없으면 null) */
            thumbnailUrl: string | null;
            /** @example image/gif */
            mimeType: string;
            /** @description 자동재생 대상 여부(움짤/영상) */
            isAnimated: boolean;
            width: number | null;
            height: number | null;
            /** @description 동영상/애니메이션 길이(ms) */
            durationMs: number | null;
        };
        PublicUserResponse: {
            id: string;
            nickname: string;
            avatarUrl: string | null;
        };
        PaginatedUsersResponse: {
            /**
             * @description 다음 페이지 커서. null이면 마지막 페이지입니다.
             * @example null
             */
            nextCursor: string | null;
            items: components["schemas"]["PublicUserResponse"][];
        };
        UserProfileResponse: {
            id: string;
            nickname: string;
            statusMessage: string | null;
            avatarUrl: string | null;
            /**
             * Format: date-time
             * @description 마지막 접속 시각
             */
            lastSeenAt: string | null;
        };
        CreateProfileDto: {
            /** @example 택이 */
            nickname: string;
            /** @example 안녕하세요 */
            statusMessage?: string;
            /** @description 아바타 미디어 id */
            avatarMediaId?: string;
        };
        ProfileResponse: {
            userId: string;
            nickname: string;
            statusMessage: string | null;
            avatarMediaId: string | null;
            /**
             * Format: date-time
             * @description null이면 온보딩 미완료
             */
            onboardedAt: string | null;
            /** Format: date-time */
            updatedAt: string;
            /** @description 표시용 아바타 URL(없으면 null) */
            avatarUrl: string | null;
        };
        UpdateProfileDto: {
            nickname?: string;
            statusMessage?: string;
            avatarMediaId?: string;
        };
        RoomMemberResponse: {
            userId: string;
            nickname: string | null;
            avatarUrl: string | null;
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "MEMBER";
        };
        RoomLastMessageResponse: {
            /** @description 룸 내 단조 증가 시퀀스 */
            seq: number;
            /** @enum {string} */
            type: "TEXT" | "IMAGE" | "GIF" | "VIDEO" | "FILE" | "SYSTEM";
            /** @description 미리보기 텍스트(삭제 시 placeholder) */
            preview: string;
            /** Format: date-time */
            createdAt: string;
        };
        RoomViewResponse: {
            id: string;
            /** @enum {string} */
            type: "DIRECT" | "GROUP";
            /** @description GROUP 방 이름 */
            name: string | null;
            avatarUrl: string | null;
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastMessageAt: string | null;
            members: components["schemas"]["RoomMemberResponse"][];
            /** @description 마지막 메시지(없으면 null) */
            lastMessage?: components["schemas"]["RoomLastMessageResponse"] | null;
            /** @description 미읽음 메시지 수 */
            unreadCount?: number;
        };
        PaginatedRoomsResponse: {
            /**
             * @description 다음 페이지 커서. null이면 마지막 페이지입니다.
             * @example null
             */
            nextCursor: string | null;
            items: components["schemas"]["RoomViewResponse"][];
        };
        CreateRoomDto: {
            /** @enum {string} */
            type: "DIRECT" | "GROUP";
            /** @description GROUP 방 이름 */
            name?: string;
            avatarMediaId?: string;
            /** @description 상대(DIRECT=1명) 또는 초대 멤버(GROUP) */
            memberUserIds: string[];
        };
        UpdateRoomDto: {
            name?: string;
            avatarMediaId?: string;
        };
        AddMembersDto: {
            userIds: string[];
        };
        UpdateMemberRoleDto: {
            /** @enum {string} */
            role: "ADMIN" | "MEMBER" | "OWNER";
        };
        MessageResponse: {
            id: string;
            roomId: string;
            senderId: string;
            /** @description 룸 내 단조 증가 시퀀스 */
            seq: number;
            /** @enum {string} */
            type: "TEXT" | "IMAGE" | "GIF" | "VIDEO" | "FILE" | "SYSTEM";
            /** @description TEXT 본문(삭제/미디어면 null) */
            content: string | null;
            mediaId: string | null;
            replyToId: string | null;
            /** @description 멱등성 키 */
            clientMessageId?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            editedAt: string | null;
            /** Format: date-time */
            deletedAt: string | null;
            /** @description 발신자 제외, 읽은 멤버 수 */
            readCount?: number;
        };
        PaginatedMessagesResponse: {
            /**
             * @description 다음 페이지 커서. null이면 마지막 페이지입니다.
             * @example null
             */
            nextCursor: string | null;
            items: components["schemas"]["MessageResponse"][];
        };
        SendMessageDto: {
            /** @description 멱등성 키(클라이언트 UUID) */
            clientMessageId?: string;
            /** @enum {string} */
            type: "TEXT" | "IMAGE" | "GIF" | "VIDEO" | "FILE";
            /** @description TEXT 본문 또는 미디어 캡션 */
            content?: string | null;
            /** @description 미디어 메시지일 때 mediaId */
            mediaId?: string | null;
            /** @description 답장 대상 메시지 id */
            replyToId?: string | null;
        };
        SendMessageResponse: {
            id: string;
            /** @description 발급된 시퀀스 */
            seq: number;
            /** Format: date-time */
            createdAt: string;
        };
        ReadDto: {
            /** @example 42 */
            lastReadSeq: number;
        };
        RegisterTokenDto: {
            fcmToken: string;
            /** @enum {string} */
            platform: "ios" | "android" | "web";
            deviceId?: string;
        };
        PushTokenResponse: {
            id: string;
            /** @enum {string} */
            platform: "ios" | "android" | "web";
        };
        CreateWhitelistDto: {
            /** @description 카카오 회원번호 */
            kakaoId?: string;
            /** @description 대체 식별자(이메일/전화 등) */
            identifier?: string;
            note?: string;
        };
        WhitelistResponse: {
            id: string;
            /** @description 카카오 회원번호 */
            kakaoId: string | null;
            /** @description 대체 식별자(이메일/전화 등) */
            identifier: string | null;
            /** @enum {string} */
            status: "INVITED" | "ACTIVE" | "BLOCKED";
            /** @description 초대한 사용자 id */
            invitedBy: string | null;
            note: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginatedWhitelistResponse: {
            /**
             * @description 다음 페이지 커서. null이면 마지막 페이지입니다.
             * @example null
             */
            nextCursor: string | null;
            items: components["schemas"]["WhitelistResponse"][];
        };
        UpdateWhitelistDto: {
            /** @enum {string} */
            status?: "INVITED" | "ACTIVE" | "BLOCKED";
            note?: string;
        };
        AccessRequestResponse: {
            id: string;
            /** @description 로그인 시도에서 확보한 카카오 회원번호 */
            kakaoId: string;
            /** @description 카카오 프로필 닉네임 */
            nickname: string | null;
            profileImageUrl: string | null;
            /** @description 누적 로그인 시도 횟수 */
            attempts: number;
            /**
             * Format: date-time
             * @description 최초 시도 시각
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 마지막 시도 시각
             */
            lastAttemptAt: string;
        };
        PaginatedAccessRequestsResponse: {
            /**
             * @description 다음 페이지 커서. null이면 마지막 페이지입니다.
             * @example null
             */
            nextCursor: string | null;
            items: components["schemas"]["AccessRequestResponse"][];
        };
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        ReadyResponse: {
            /** @example ready */
            status: string;
            /** @description DB 연결 가능 여부 */
            db: boolean;
            /** @description Redis 연결 가능 여부 */
            redis: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_kakao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KakaoLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutDto"];
            };
        };
        responses: {
            /** @description 로그아웃 완료(본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    MediaController_createUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadUrlDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrlResponse"];
                };
            };
        };
    };
    MediaController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResponse"];
                };
            };
        };
    };
    MediaController_getMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResponse"];
                };
            };
        };
    };
    UsersController_search: {
        parameters: {
            query: {
                /** @description 커서(seq 또는 id 또는 ISO 타임스탬프) */
                cursor?: string;
                /** @description 페이지 크기 */
                limit?: number;
                /** @description 검색 키워드(닉네임) */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUsersResponse"];
                };
            };
        };
    };
    UsersController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    ProfileController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProfileDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    ProfileController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    RoomsController_list: {
        parameters: {
            query?: {
                /** @description 커서(seq 또는 id 또는 ISO 타임스탬프) */
                cursor?: string;
                /** @description 페이지 크기 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRoomsResponse"];
                };
            };
        };
    };
    RoomsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomViewResponse"];
                };
            };
        };
    };
    RoomsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomViewResponse"];
                };
            };
        };
    };
    RoomsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoomDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomViewResponse"];
                };
            };
        };
    };
    RoomsController_addMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMembersDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomViewResponse"];
                };
            };
        };
    };
    RoomsController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 탈퇴/추방 완료(본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoomsController_updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomViewResponse"];
                };
            };
        };
    };
    MessagesController_list: {
        parameters: {
            query?: {
                /** @description 커서(seq 또는 id 또는 ISO 타임스탬프) */
                cursor?: string;
                /** @description 페이지 크기 */
                limit?: number;
            };
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMessagesResponse"];
                };
            };
        };
    };
    MessagesController_send: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
        };
    };
    MessagesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
                messageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 언센드 완료(본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MessagesController_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadDto"];
            };
        };
        responses: {
            /** @description 읽음 위치 갱신 완료(본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PushController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterTokenDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushTokenResponse"];
                };
            };
        };
    };
    PushController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료(본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_list: {
        parameters: {
            query?: {
                /** @description 커서(seq 또는 id 또는 ISO 타임스탬프) */
                cursor?: string;
                /** @description 페이지 크기 */
                limit?: number;
                status?: "INVITED" | "ACTIVE" | "BLOCKED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWhitelistResponse"];
                };
            };
        };
    };
    AdminController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWhitelistDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitelistResponse"];
                };
            };
        };
    };
    AdminController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료(본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWhitelistDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitelistResponse"];
                };
            };
        };
    };
    AccessRequestController_list: {
        parameters: {
            query?: {
                /** @description 커서(seq 또는 id 또는 ISO 타임스탬프) */
                cursor?: string;
                /** @description 페이지 크기 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccessRequestsResponse"];
                };
            };
        };
    };
    AccessRequestController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitelistResponse"];
                };
            };
        };
    };
    AccessRequestController_dismiss: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료(본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
}
